#!/usr/bin/env python
"""Export a Singular script computing the FULL tangent (logarithmic derivation) module.

Part C of the External Int2 audit. The production tangent fields come from the bounded
ansatz ``generate_tangent_fields(family, ((1,1),(2,2)))`` — linear algebra that is complete
WITHIN each degree block but says nothing about generators of higher degree. The complete
object is the kernel of the map

    R^(nvars+npolys) -> R^npolys,   (Q, H) |-> ( Q . grad G_l  -  H_l G_l )_l ,

over ``R = Q(r)[x2,x5,x7]`` — a syzygy computation (``syz`` of the columns of the 4x7
condition matrix). Singular is not installed on this machine, so this exporter writes the
ready-to-run script ``scripts/external_int2_tangent_module.sing``; running it elsewhere
(``Singular -q external_int2_tangent_module.sing``) prints a minimal generating set, whose
Q-part degrees decide whether the (1,1)/(2,2) ansatz already generates the module.

The polynomial text is rendered from the PARSED family (never hand-transcribed).
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import sympy as sp

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

INPUT_FILE = REPO_ROOT / "examples" / "external_int2_dimensionless_input.wl.txt"
DEFAULT_OUT = REPO_ROOT / "scripts" / "external_int2_tangent_module.sing"


def _load_t2_module():
    name = "run_external_int2_t2_rankrepair"
    if name in sys.modules:
        return sys.modules[name]
    path = Path(__file__).resolve().parent / "run_external_int2_t2_rankrepair.py"
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def _singular_poly(expr: sp.Expr) -> str:
    """Render a sympy polynomial in Singular syntax (integer/rational coeffs, ``^``)."""
    return sp.sstr(sp.expand(expr)).replace("**", "^")


def render_sing(family) -> str:
    variables = list(family.variables)
    params = [p for p in family.parameters if p != "ep"]  # exponents' ep never enters G_l
    names = list(family.poly_names)
    nvars, npolys = family.nvars, family.npolys
    g_sym = {n: family.polynomials[n].to_sympy(variables) for n in names}
    for n in names:
        extra = g_sym[n].free_symbols - {sp.Symbol(v) for v in variables} - {sp.Symbol(p) for p in params}
        if extra:
            raise ValueError(f"unexpected symbols {extra} in {n}")

    par = ",".join(["0"] + params) if params else "0"
    lines = [
        "// AUTO-GENERATED by scripts/export_external_int2_tangent_module.py — do not edit.",
        "// Full tangent (log-derivation) module for the External Int2 divisor {prod G_l = 0}.",
        "// Kernel of (Q,H) |-> (Q.grad G_l - H_l G_l)_l  ==  syz of the condition-matrix columns.",
        "// Run:  Singular -q external_int2_tangent_module.sing",
        f'ring R = ({par}),({",".join(variables)}),dp;',
    ]
    for n in names:
        lines.append(f"poly {n} = {_singular_poly(g_sym[n])};")
    lines.append(f"list Gs = {','.join(names)};")
    ncols = nvars + npolys
    lines += [
        f"matrix A[{npolys}][{ncols}];",
        "int l;",
        f"for (l = 1; l <= {npolys}; l++) {{",
    ]
    for j, v in enumerate(variables, start=1):
        lines.append(f"  A[l,{j}] = diff(Gs[l], {v});")
    lines += [
        f"  A[l,{nvars}+l] = -Gs[l];",
        "}",
        "module K = syz(module(A));",
        "module KM = minbase(K);",
        f'print("== minimal generators of the tangent module (rows 1..{nvars} = Q, rows {nvars + 1}..{ncols} = H) ==");',
        "print(KM);",
        'print("== Q-part x-degrees per generator (compare with ansatz blocks (1,1),(2,2)) ==");',
        "int k;",
        "for (k = 1; k <= size(KM); k++) {",
        f"  int dq = -1; for (l = 1; l <= {nvars}; l++) {{ if (deg(KM[k][l]) > dq) {{ dq = deg(KM[k][l]); }} }}",
        '  print("gen " + string(k) + ": deg_x Q = " + string(dq));',
        "  kill dq;",
        "}",
        "quit;",
    ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    out = Path(argv[0]) if argv else DEFAULT_OUT
    T2 = _load_t2_module()
    family = T2.parse_family_text(INPUT_FILE.read_text(encoding="utf-8"))
    out.write_text(render_sing(family), encoding="utf-8", newline="\n")
    print(f"[tangent-module] Singular script -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
